# Generated by Django 6.1.1 on 2026-09-30 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('address', models.TextField()),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theaters', to='theaters.city')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('total_rows', models.PositiveIntegerField(default=10)),
                ('seats_per_row', models.PositiveIntegerField(default=12)),
                ('is_active', models.BooleanField(default=True)),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='theaters.theater')),
            ],
            options={
                'ordering': ['theater', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=5)),
                ('number', models.PositiveIntegerField()),
                ('seat_type', models.CharField(choices=[('regular', 'Regular'), ('premium', 'Premium'), ('recliner', 'Recliner'), ('vip', 'VIP')], default='regular', max_length=20)),
                ('price_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='theaters.screen')),
            ],
            options={
                'ordering': ['row', 'number'],
                'indexes': [models.Index(fields=['screen', 'row', 'number'], name='theaters_se_screen__daf8c9_idx')],
                'unique_together': {('screen', 'row', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_date', models.DateField()),
                ('show_time', models.TimeField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.language')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='movies.movie')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='theaters.screen')),
            ],
            options={
                'ordering': ['show_date', 'show_time'],
                'indexes': [models.Index(fields=['movie', 'show_date', 'is_active'], name='theaters_sh_movie_i_62a1dc_idx'), models.Index(fields=['screen', 'show_date', 'show_time'], name='theaters_sh_screen__1758f1_idx'), models.Index(fields=['show_date', 'show_time'], name='theaters_sh_show_da_e9c219_idx')],
                'unique_together': {('screen', 'show_date', 'show_time')},
            },
        ),
        migrations.AddIndex(
            model_name='theater',
            index=models.Index(fields=['city', 'is_active'], name='theaters_th_city_id_014a38_idx'),
        ),
        migrations.AddIndex(
            model_name='theater',
            index=models.Index(fields=['slug'], name='theaters_th_slug_3dd4ac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='screen',
            unique_together={('theater', 'name')},
        ),
    ]
