# Generated by Django 6.1.1 on 2026-09-30 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('theaters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('seats_count', models.PositiveIntegerField(default=0)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('pdf_ticket', models.FileField(blank=True, null=True, upload_to='tickets/')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='theaters.show')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-booked_at'],
            },
        ),
        migrations.CreateModel(
            name='SeatReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Available'), ('held', 'Temporarily Held'), ('booked', 'Booked')], default='available', max_length=20)),
                ('held_at', models.DateTimeField(blank=True, null=True)),
                ('held_until', models.DateTimeField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seat_reservations', to='bookings.booking')),
                ('held_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_seats', to=settings.AUTH_USER_MODEL)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='theaters.seat')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_reservations', to='theaters.show')),
            ],
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'status'], name='bookings_bo_user_id_69a5d5_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['show', 'status'], name='bookings_bo_show_id_d9a7dc_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_id'], name='bookings_bo_booking_eb8fc3_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'expires_at'], name='bookings_bo_status_86acff_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booked_at'], name='bookings_bo_booked__6ab0fd_idx'),
        ),
        migrations.AddIndex(
            model_name='seatreservation',
            index=models.Index(fields=['show', 'status'], name='bookings_se_show_id_b9ecfa_idx'),
        ),
        migrations.AddIndex(
            model_name='seatreservation',
            index=models.Index(fields=['held_until'], name='bookings_se_held_un_69ffdf_idx'),
        ),
        migrations.AddIndex(
            model_name='seatreservation',
            index=models.Index(fields=['booking'], name='bookings_se_booking_47444d_idx'),
        ),
        migrations.AddIndex(
            model_name='seatreservation',
            index=models.Index(fields=['show', 'seat', 'status'], name='bookings_se_show_id_bb6dee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='seatreservation',
            unique_together={('show', 'seat')},
        ),
    ]
