# Generated by Django 6.1.1 on 2026-09-30 16:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cast/')),
                ('bio', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Cast',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField()),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('release_date', models.DateField()),
                ('certification', models.CharField(choices=[('U', 'U - Universal'), ('UA', 'UA - Parental Guidance'), ('A', 'A - Adults Only'), ('S', 'S - Restricted')], default='UA', max_length=5)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('now_showing', 'Now Showing'), ('archived', 'Archived')], default='upcoming', max_length=20)),
                ('trailer_url', models.URLField(blank=True, help_text='YouTube embed URL or watch URL')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_ratings', models.PositiveIntegerField(default=0)),
                ('is_trending', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(related_name='movies', to='movies.genre')),
                ('languages', models.ManyToManyField(related_name='movies', to='movies.language')),
            ],
            options={
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='MovieCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('actor', 'Actor'), ('actress', 'Actress'), ('director', 'Director'), ('producer', 'Producer'), ('writer', 'Writer')], default='actor', max_length=20)),
                ('character_name', models.CharField(blank=True, max_length=100)),
                ('cast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.cast')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
            options={
                'unique_together': {('movie', 'cast', 'role')},
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(related_name='movies', through='movies.MovieCast', to='movies.cast'),
        ),
        migrations.CreateModel(
            name='MoviePoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='posters/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posters', to='movies.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('is_verified', models.BooleanField(default=False, help_text='User has booked this movie')),
                ('is_approved', models.BooleanField(default=True)),
                ('is_reported', models.BooleanField(default=False)),
                ('report_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['status', 'release_date'], name='movies_movi_status_66fc0c_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['is_trending'], name='movies_movi_is_tren_c5976e_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['average_rating'], name='movies_movi_average_7da280_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['slug'], name='movies_movi_slug_5ef9c7_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['movie', 'is_approved'], name='movies_revi_movie_i_0ac898_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user'], name='movies_revi_user_id_20caf3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('movie', 'user')},
        ),
    ]
